FROM ghcr.io/parkervcp/yolks:nodejs_20

LABEL author="catzoo"

USER root

RUN apt update && apt install -y gcc g++ libgcc1 libc++-dev gdb libc6 git wget curl tar zip unzip binutils xz-utils liblzo2-2 cabextract iproute2 net-tools libatomic1 libsdl1.2debian libsdl2-2.0-0 \
	libfontconfig icu-devtools libunwind8 libzip4 locales ffmpeg apt-transport-https init-system-helpers \
	libcurl3-gnutls liblua5.1-0 libluajit-5.1-2 libsqlite3-0 bzip2 zlib1g libevent-dev libmariadb-dev-compat libmariadb-dev libssl-dev \
	libfluidsynth-dev libmariadb-dev libicu-dev libssl3 libduktape207 libjsoncpp-dev libleveldb1d libncurses5 libncursesw5

RUN npm i -g omegga

COPY          --chown=container:container entrypoint.sh /entrypoint.sh
RUN           chmod +x /entrypoint.sh
ENTRYPOINT    ["/usr/bin/tini", "-g", "--"]
CMD           ["/entrypoint.sh"]

USER container

