FROM ghcr.io/pelican-eggs/yolks:nodejs_24

LABEL author="catzoo"

USER root

# RUN apt update && apt install -y gcc g++ libgcc1 libc++-dev gdb libc6 git wget curl tar zip unzip binutils xz-utils liblzo2-2 cabextract iproute2 net-tools libatomic1 libsdl1.2debian libsdl2-2.0-0 \
# 	libfontconfig icu-devtools libunwind8 libzip4 locales ffmpeg apt-transport-https init-system-helpers \
# 	libcurl3-gnutls liblua5.1-0 libluajit-5.1-2 libsqlite3-0 bzip2 zlib1g libevent-dev libmariadb-dev-compat libmariadb-dev libssl-dev \
# 	libfluidsynth-dev libmariadb-dev libicu-dev libssl3 libduktape207 libjsoncpp-dev libleveldb1d libncurses5 libncursesw5 yq lib32gcc-s1

RUN apt update && apt install -y lib32gcc-s1 wget tar
RUN wget https://github.com/mikefarah/yq/releases/download/v4.45.1/yq_linux_amd64 -O /usr/bin/yq
RUN chmod +x /usr/bin/yq

RUN mkdir /omegga; chown container /omegga

USER container

ENV PATH=/omegga/bin:$PATH
RUN npm config set prefix /omegga
RUN npm i -g omegga

COPY          --chown=container:container --chmod=+x entrypoint.sh /entrypoint.sh
ENTRYPOINT    ["/usr/bin/tini", "-g", "--"]
CMD           ["/entrypoint.sh"]
